version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - database  # Add if you're using a database

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  # Optional: Add database service if needed
  # database:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: yourdbname
  #     POSTGRES_PASSWORD: yourpassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
  # postgres-data:  # Uncomment if using database